apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: your-app-rollout
  namespace: flyway-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: your-app-image:latest
          ports:
            - containerPort: 8080
          # aquí tus vars de conexión si la app las necesita
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {duration: 10s}
        - setWeight: 50
        - pause: {duration: 10s}
        - setWeight: 100
