apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway-migrations
  labels:
    app: flyway-migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyway-migrations
  template:
    metadata:
      labels:
        app: flyway-migrations
    spec:
      containers:
      - name: flyway
        image: flyway-migrations:latest
        imagePullPolicy: Always
        env:
        - name: FLYWAY_ENV
          value: prod
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: schema
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  schema: public
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL215ZGF0YWJhc2U=  # jdbc:postgresql://postgres-service:5432/mydatabase
  username: cG9zdGdyZXM=  # postgres
  password: Y2hhbmdlbWU=  # changeme