apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-config
  namespace: flyway-dev
data:
  # Solo parámetros que cambian por entorno
  flyway.url: "jdbc:postgresql://postgres-dev:5432/mydatabase"
  flyway.user: "postgres"
  flyway.password: "postgres"
  flyway.schemas: "public"