apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
  namespace: flyway-dev
spec:
  template:
    spec:
      containers:
      - name: flyway
        image: flyway-migrations:local
        imagePullPolicy: IfNotPresent
        env:
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: flyway.url
        - name: FLYWAY_USER
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: flyway.user
        - name: FLYWAY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: flyway.password
        - name: FLYWAY_SCHEMAS
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: flyway.schemas
        command:
        - flyway
        - -configFiles=/flyway/conf/flyway.conf   # base options baked into image
        - -url=$(FLYWAY_URL)
        - -user=$(FLYWAY_USER)
        - -password=$(FLYWAY_PASSWORD)
        - -schemas=$(FLYWAY_SCHEMAS)
        - migrate
      restartPolicy: Never
