apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: flyway-dev

secretGenerator:
  - name: db-credentials
    behavior: replace
    literals:
      - url=jdbc:postgresql://172.29.140.116:5432/mydatabase
      - username=dev_user
      - password=dev_password