name: CI/CD Pipeline for Flyway

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate DB Migrations
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Validate Flyway Migrations
        uses: docker://flyway/flyway:9.20.0-alpine
        with:
          args: >
            -url=jdbc:postgresql://postgres:5432/mydatabase
            -user=postgres
            -password=postgres
            -connectRetries=60
            validate

      - name: Flyway Info
        uses: docker://flyway/flyway:9.20.0-alpine
        with:
          args: >
            -url=jdbc:postgresql://postgres:5432/mydatabase
            -user=postgres
            -password=postgres
            info

      - name: Test Migrations
        uses: docker://flyway/flyway:9.20.0-alpine
        with:
          args: >
            -url=jdbc:postgresql://postgres:5432/mydatabase
            -user=postgres
            -password=postgres
            migrate

  build-deploy:
    name: Build & Deploy to Minikube
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # 1) Instalar kubectl y Minikube
      - name: Install kubectl & Minikube
        run: |
          # kubectl
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          # Minikube
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube && sudo mv minikube /usr/local/bin/

      # 2) Iniciar Minikube
      - name: Start Minikube
        run: minikube start --driver=docker

      # 3) Configurar Docker dentro de Minikube
      - name: Configure Docker to Minikube
        run: eval $(minikube docker-env)

      # 4) Construir imagen Docker
      - name: Build Docker Image
        run: docker build -t flyway-migrations:local .

      # 5) Instalar Argo Rollouts CRDs
      - name: Install Argo Rollouts CRDs
        run: |
          kubectl apply -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml

      # 6) Crear el namespace (si ya existe, no falla)
      - name: Ensure namespace flyway-dev
        run: |
          kubectl create namespace flyway-dev || echo "namespace flyway-dev already exists"

      # 7) Verificar cluster
      - name: Validate kubectl context
        run: |
          kubectl cluster-info
          kubectl get nodes

      # 8) Desplegar con Kustomize
      - name: Deploy to Minikube
        run: kubectl apply -k k8s/overlays/dev
